User.create!([
  {name: "Gus Chiggins", email: "user1@example.com", goal: 175, password:"password", goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"10", profile_pic:"/public/gus_chiggins.png"},
  {name: "Ben White", email: "user2@example.com", password:"password", goal: 150, goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"7", profile_pic:"/assets/ben.jpg"},
  {name: "Matz", email: "user3@example.com", password:"password", goal: 160, goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"10", profile_pic:"/assets/matz.jpg"},
  {name: "Tom Hanlon", email: "user4@example.com", password:"password", goal: 175, goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"11", profile_pic:"/assets/tom_h.jpg"},
  {name: "Casey McNeil", email: "user5@example.com", password:"password", goal: 165, goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"9", profile_pic:"/assets/casey_m.jpg"},
  {name: "Kelly Rytlewski", email: "user6@example.com", password:"password", goal: 115, goal_date:"2014-03-01", height_in_feet:"5", height_in_inches:"5", profile_pic:"/assets/kelly_r.jpg"},
])
Friendship.create!([
  {user_id: 1, friend_id: 4},
  {user_id: 4, friend_id: 1},
  {user_id: 5, friend_id: 4},
  {user_id: 4, friend_id: 5},
  {user_id: 2, friend_id: 5},
  {user_id: 5, friend_id: 2},
  {user_id: 3, friend_id: 5},
  {user_id: 5, friend_id: 3},
  {user_id: 6, friend_id: 2},
  {user_id: 2, friend_id: 6},
  {user_id: 6, friend_id: 3},
  {user_id: 3, friend_id: 6},
  {user_id: 6, friend_id: 5},
  {user_id: 5, friend_id: 6},
])
WeighIn.create!([
  {weight: 130, pic_url: nil, user_id: 6, status: 'Lorem ipsum dolor sit amet', date: nil, created_at: (Time.now - 10.days)},
  {weight: 129, pic_url: nil, user_id: 6, status: 'Lorem ipsum dolor sit amet', date: nil, created_at: (Time.now - 9.days)},
  {weight: 126, pic_url: nil, user_id: 6, status: 'Lorem ipsum dolor sit amet', date: nil, created_at: (Time.now - 8.days)},
  {weight: 125, pic_url: nil, user_id: 6, status: 'Lorem ipsum dolor sit amet', date: nil, created_at: (Time.now - 7.days)},
  {weight: 125, pic_url: nil, user_id: 6, status: 'Lorem ipsum dolor sit amet', date: nil, created_at: (Time.now - 6.days)},
  {weight: 124, pic_url: nil, user_id: 6, status: 'I cant believe those pants used to fit', date: nil, created_at: (Time.now - 5.days)},
  {weight: 126, pic_url: nil, user_id: 6, status: 'the pounds are melting off', date: nil, created_at: (Time.now - 4.days)},
  {weight: 123, pic_url: nil, user_id: 6, status: 'Looking cut', date: nil, created_at: (Time.now - 3.days)},
  {weight: 122, pic_url: nil, user_id: 6, status: 'Gettn ready for the Summer!', date: nil, created_at: (Time.now - 2.days)},
  {weight: 119, pic_url: nil, user_id: 6, status: 'Just got back from the gym', date: nil, created_at: (Time.now - 1.days)},
  {weight: 192, pic_url: nil, user_id: 5, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 189, pic_url: nil, user_id: 5, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 184, pic_url: nil, user_id: 5, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 187, pic_url: nil, user_id: 5, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 192, pic_url: nil, user_id: 5, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 185, pic_url: nil, user_id: 5, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 181, pic_url: nil, user_id: 5, status: 'Need this accountability so bad....', date: nil},
  {weight: 185, pic_url: nil, user_id: 5, status: "Gym tan laundry", date: nil},
  {weight: 182, pic_url: nil, user_id: 5, status: "Glad to finally see some progress", date: nil},
  {weight: 181, pic_url: nil, user_id: 5, status: 'Im starting to miss carbs', date: nil},
  {weight: 180, pic_url: nil, user_id: 5, status: '', date: nil},
  {weight: 192, pic_url: nil, user_id: 4, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 189, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 184, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 187, pic_url: nil, user_id: 4, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 192, pic_url: nil, user_id: 4, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 185, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 181, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 185, pic_url: nil, user_id: 4, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 182, pic_url: nil, user_id: 4, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 181, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 180, pic_url: nil, user_id: 4, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 192, pic_url: nil, user_id: 3, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 189, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 184, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 187, pic_url: nil, user_id: 3, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 192, pic_url: nil, user_id: 3, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 185, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 181, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 185, pic_url: nil, user_id: 3, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 182, pic_url: nil, user_id: 3, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 181, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 180, pic_url: nil, user_id: 3, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 180, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 176, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},  
  {weight: 176, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 174, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},  
  {weight: 173, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 170, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},  
  {weight: 173, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 170, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},  
  {weight: 169, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 171, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},  
  {weight: 167, pic_url: nil, user_id: 2, status: 'Lorem ipsum dolor sit amet', date: nil},
  {weight: 165, pic_url: nil, user_id: 2, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 195, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 194, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 192, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 190, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 186, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 189, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 185, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 183, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 181, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 185, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil},
  {weight: 180, pic_url: nil, user_id: 1, status: "Lorem ipsum dolor sit amet", date: nil}
])

Comment.create!([
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 1, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 1, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 2, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 2, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 2, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 3, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 3, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 4, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 4, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 5, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 5, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 6, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 6, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 6, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 7, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 7, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 8, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 8, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 9, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 9, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 4, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 4, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 10, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 10, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 10, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 11, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 11, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 12, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 12, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 13, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 13, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 14, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 14, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 1, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 15, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 15, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 16, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 16, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 17, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 17, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 18, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 18, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 19, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 19, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 20, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 20, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 20, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 21, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 21, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 22, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 22, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 23, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 23, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 23, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 24, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 24, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 25, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 25, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 26, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 26, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 27, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 27, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 27, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 28, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 28, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 29, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 29, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 23, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 23, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 31, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 31, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 32, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 32, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 33, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 33, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 34, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 34, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 35, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 35, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 35, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 36, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 36, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 37, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 37, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 38, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 38, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 39, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 39, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 39, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 40, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 40, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 41, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 41, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 42, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 42, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 43, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 43, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 43, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 44, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 44, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 48, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 48, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 49, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 49, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 50, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 50, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 51, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 51, user_id: 5},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 52, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 52, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 52, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 53, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 54, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 54, user_id: 6},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 55, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 55, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 56, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 56, user_id: 4},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 57, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 57, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 57, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 57, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 58, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 59, user_id: 3},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 59, user_id: 2},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 60, user_id: 1},
  {body:"Lorem ipsum dolor sit amet", weigh_in_id: 60, user_id: 5},
])

WiYeehaw.create!([
  { weigh_in_id: 6, user_id: 4},
  { weigh_in_id: 5, user_id: 4},
  { weigh_in_id: 2, user_id: 2},
  { weigh_in_id: 52, user_id: 3},
  { weigh_in_id: 11, user_id: 3},
  { weigh_in_id: 50, user_id: 1},
  { weigh_in_id: 23, user_id: 1},
  { weigh_in_id: 54, user_id: 1},
  { weigh_in_id: 54, user_id: 6},
  { weigh_in_id: 12, user_id: 1},
  { weigh_in_id: 42, user_id: 3},
  { weigh_in_id: 43, user_id: 2},
  { weigh_in_id: 43, user_id: 5},
  { weigh_in_id: 43, user_id: 5},
  { weigh_in_id: 44, user_id: 1},
  { weigh_in_id: 34, user_id: 6},
  { weigh_in_id: 3, user_id: 5},
  { weigh_in_id: 35, user_id: 1},
  { weigh_in_id: 15, user_id: 1},
  { weigh_in_id: 35, user_id: 2},
  { weigh_in_id: 36, user_id: 2},
  { weigh_in_id: 26, user_id: 5},
  { weigh_in_id: 31, user_id:4},
  { weigh_in_id: 32, user_id: 2},
  { weigh_in_id: 32, user_id: 3},
  { weigh_in_id: 13, user_id: 2},
  { weigh_in_id: 33, user_id: 1},
  { weigh_in_id: 14, user_id: 6},
  { weigh_in_id: 24, user_id: 5},
  { weigh_in_id: 35, user_id: 1},
  { weigh_in_id: 3, user_id: 1},
])